// Generated by CoffeeScript 1.12.7
let container;
let liquid;

(function() {
  let fill;

  fill = function(container, liquid) {
    if (liquid == null) {
      liquid = "coffee";
      
    }
    return "Filling the " + container + " with " + liquid;
  };

  

  module.exports = fill;

}).call(this);
